version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "ci"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "deps"
  groups:
    vite:
      patterns:
      - "@vitejs/*"
      - "vite"
    vitest:
      patterns:
      - "@vitest/*"
      - "vitest"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    redux:
      patterns:
      - "redux"
      - "redux-thunk"
      - "react-redux"
      - "@reduxjs/*"
      - "reselect"
    mui:
      patterns:
      - "@mui/*"
    markdown:
      patterns:
      - "react-markdown"
      - "remark-*"
      - "rehype-*"
    babel:
      patterns:
      - "@babel/*"
    eslint:
      patterns:
      - "eslint"
      - "eslint-plugin-*"
      - "eslint-config-*"
      - "@typescript-eslint/*"
    stylelint:
      patterns:
      - "stylelint"
      - "stylelint-config-*"
