version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "ci"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "deps"
  groups:
    vitest:
      patterns:
      - "@vitest/*"
      - "vitest"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    mui:
      patterns:
      - "@mui/*"
    babel:
      patterns:
      - "@babel/*"
    stylelint:
      patterns:
      - "stylelint"
      - "stylelint-config-*"
