version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "ci"
- package-ecosystem: npm
  directories: ["/", "/npm"]
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "deps"
  ignore:
    # Minimum node.js version is updated manually
    - dependency-name: "@types/node"
  groups:
    non-major:
      update-types: [minor, patch]
    vite:
      patterns:
      - "@vitejs/*"
      - "vite"
    vitest:
      patterns:
      - "@vitest/*"
      - "vitest"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    redux:
      patterns:
      - "redux"
      - "redux-thunk"
      - "react-redux"
      - "@reduxjs/*"
      - "reselect"
    emotion:
      patterns:
      - "@emotion/*"
    mui:
      patterns:
      - "@mui/*"
    markdown:
      patterns:
      - "react-markdown"
      - "remark-*"
      - "rehype-*"
    react-compiler:
      patterns:
      - "react-compiler-runtime"
      - "babel-plugin-react-compiler"
      - "eslint-plugin-react-compiler"
    babel:
      patterns:
      - "@babel/*"
    eslint:
      patterns:
      - "eslint"
      - "eslint-plugin-*"
      - "eslint-config-*"
      - "@eslint/*"
      - "@typescript-eslint/*"
      - "typescript-eslint"
    stylelint:
      patterns:
      - "stylelint"
      - "stylelint-config-*"
    pragmatic-dnd:
      patterns:
      - "@atlaskit/pragmatic-drag-and-drop"
      - "@atlaskit/pragmatic-drag-and-drop-*"
