export const SOCKET_CONNECT = 'auth/SOCKET_CONNECT';
export const SOCKET_RECONNECT = 'auth/SOCKET_RECONNECT';
export const SOCKET_CONNECTED = 'auth/SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'auth/SOCKET_DISCONNECTED';

export const SET_TOKEN = 'auth/SET_TOKEN';

export const RESET_PASSWORD_COMPLETE = 'auth/RESET_PASSWORD_COMPLETE';
