export const PLAYLIST = 'youtube/import/PLAYLIST';
export const CHANNEL = 'youtube/import/CHANNEL';

export const GET_IMPORTABLE_PLAYLIST_START = 'youtube/import/GET_IMPORTABLE_PLAYLIST_START';
export const GET_IMPORTABLE_PLAYLIST_COMPLETE = 'youtube/import/GET_IMPORTABLE_PLAYLIST_COMPLETE';

export const GET_CHANNEL_PLAYLISTS_START = 'youtube/import/GET_CHANNEL_PLAYLISTS_START';
export const GET_CHANNEL_PLAYLISTS_COMPLETE = 'youtube/import/GET_CHANNEL_PLAYLISTS_COMPLETE';

export const IMPORT_PLAYLIST_START = 'youtube/import/IMPORT_PLAYLIST_START';
export const IMPORT_PLAYLIST_COMPLETE = 'youtube/import/IMPORT_PLAYLIST_COMPLETE';

export const SET_AVAILABLE_QUALITY_LEVELS = 'youtube/SET_AVAILABLE_QUALITY_LEVELS';
export const SET_CURRENT_QUALITY_LEVEL = 'youtube/SET_CURRENT_QUALITY_LEVEL';
export const SET_PREFERRED_QUALITY_LEVEL = 'youtube/SET_PREFERRED_QUALITY_LEVEL';
