import React from 'react';
import Uwave from './Uwave';
import experimentalThemePlugin from './experimentalThemePlugin';
import youTubeSource from './sources/youtube';
import soundCloudSource from './sources/soundcloud';

const uw = new Uwave({
  apiUrl: 'https://u-wave-demo.now.sh/api',
  socketUrl: 'wss://u-wave-demo.now.sh',
  emoji: {},
});

// Add experimental theming API.
uw.use(experimentalThemePlugin);

// Configure the Media sources to be used by this üWave client instance.
uw.source(youTubeSource());
uw.source(soundCloudSource());

uw.setAboutPageComponent(() => (
  <React.Fragment>
    <h2>Size report</h2>
    <p>Generated by webpack-bundle-analyzer. <a href="/report.html" target="_blank">View size report</a></p>
  </React.Fragment>
));

window.uw = uw;

uw.build().then(() => {
  uw.renderToDOM(document.querySelector('#app'));
  document.querySelector('#app-loading').innerHTML = '';
  document.querySelector('#jss').textContent = '';
}).catch((err) => {
  document.querySelector('.LoadingScreen-notice').textContent = `Error: ${err.message}`;

  setTimeout(() => {
    throw err;
  }, 0);
});
