import React from 'react';
import Uwave from './Uwave';
import load from './loadingUI';
import experimentalThemePlugin from './experimentalThemePlugin';
import youTubeSource from './sources/youtube';
import soundCloudSource from './sources/soundcloud';

// eslint-disable-next-line compat/compat
const url = new URL(window.location.href);
const apiUrl = url.searchParams.get('apiUrl') || 'https://u-wave-demo.fly.dev/api';
const socketUrl = url.searchParams.get('socketUrl') || 'wss://u-wave-demo.fly.dev';

const uw = new Uwave({
  apiUrl,
  socketUrl,
  emoji: {},
});

// Add experimental theming API.
uw.use(experimentalThemePlugin);

// Configure the Media sources to be used by this üWave client instance.
uw.source(youTubeSource());
uw.source(soundCloudSource());

uw.setAboutPageComponent(() => (
  <>
    <h2>Size report</h2>
    <p>Generated by webpack-bundle-analyzer. <a href="/report.html" target="_blank">View size report</a></p>
  </>
));

window.uw = uw;

load(uw).catch((err) => {
  setTimeout(() => {
    throw err;
  }, 0);
});
