name: CI

on:
  push:
    branches: [default]
  pull_request:
    branches: [default]

permissions:
  contents: read

env:
  NODE_OPTIONS: '--unhandled-rejections=strict'

jobs:
  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run typecheck

  lint:
    name: Code style
    runs-on: ubuntu-latest
    needs: [test, types]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Check code style
        run: npm run lint

  test:
    name: Tests
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run tests-only -- --coverage

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write
    needs: [test, types]

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  netlify:
    name: Deploy demo
    runs-on: ubuntu-latest
    needs: [test, types]
    permissions:
      checks: write
      statuses: write
    steps:
    - uses: actions/checkout@v7
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run prod
      env:
        VITE_DEMO: 1
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './npm/public'
        production-branch: 'default'
        github-token: ${{secrets.GITHUB_TOKEN}}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
      timeout-minutes: 1
