name: Deploy previews

on:
  repository_dispatch:
    types: [deploy-preview]

env:
  NODE_OPTIONS: '--unhandled-rejections=strict'

jobs:
  netlify:
    runs-on: ubuntu-latest
    steps:
    - name: Clone downstream repository
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.client_payload.repository}}
    - name: Checkout sources
      run: git checkout ${{github.event.client_payload.sha}}
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run prod
      env:
        DEMO: 1
        ANALYZE: 1
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './packages/u-wave-web-middleware/public'
        production-branch: 'default'
        alias: deploy-preview-${{github.event.client_payload.sha}}
        github-token: ${{secrets.GITHUB_TOKEN}}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
      timeout-minutes: 1
