name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: stable
    - name: ESLint
      run: |
        npm install
        npx eslint --format ./tasks/eslint-formatter-actions .
