name: Deploy PR Preview
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Start deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: u-wave/web
          payload: '{"sha": "${{github.sha}}", "repository": "${{github.event.pull_request.head.repo.full_name}}"}'
